apiVersion: v1
name: vault-instance
description: a chart for creating a Vault instance via the vault operator
version: 1.0.19
appVersion: 1.0.19
keywords:
  - vault
home: https://github.com/jenkins-x-charts/vault-instance
sources:
  - https://github.com/enkins-x-charts/vault-instance
